/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_meitu_base_util_YUVUtil */

#ifndef _Included_com_meitu_base_util_YUVUtil
#define _Included_com_meitu_base_util_YUVUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_meitu_base_util_YUVUtil
 * Method:    YUV2TextureId
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_com_meitu_base_util_YUVUtil_YUV2TextureId
  (JNIEnv *, jclass, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
